<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>CS8600;CS8601;CS8602;CS8603;CS8604;CS8618;CS8622;CS8625;CS8619;CS8632;CS0219;WFO1000</NoWarn>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Civil3D_Tools</AssemblyName>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App"></FrameworkReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="accoremgd">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\accoremgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AcCui">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\AcCui.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Acdbmgd">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\acdbmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="acdbmgdbrep">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\acdbmgdbrep.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Acmgd">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\acmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AecBaseMgd">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\ACA\AecBaseMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AeccDbMgd">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\C3D\AeccDbMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AeccDataShortcutMgd">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\C3D\AeccDataShortcutMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AdWindows">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\AdWindows.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AecPropDataMgd">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\ACA\AecPropDataMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Autodesk.AutoCAD.Interop">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\Autodesk.AutoCAD.Interop.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Autodesk.AutoCAD.Interop.Common">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\Autodesk.AutoCAD.Interop.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ManagedMapApi">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\Map\ManagedMapApi.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OSGeo.MapGuide.Geometry">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\Map\bin\GisPlatform\OSGeo.MapGuide.Geometry.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OSGeo.MapGuide.PlatformBase">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\Map\bin\GisPlatform\OSGeo.MapGuide.PlatformBase.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="OSGeo.MapGuide.Foundation">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\Map\bin\GisPlatform\OSGeo.MapGuide.Foundation.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Autodesk.Map.Platform">
      <HintPath>C:\Program Files\Autodesk\AutoCAD 2027\Map\Autodesk.Map.Platform.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="ExcelNumberFormat" Version="1.1.0" />
  </ItemGroup>
</Project>
